### ISSUE TITLE
MorgenCore Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#10]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by herasymj** [comment]
Observations: Contains a lot of useful little functions that we will most likely use throughout the project (number randomizing, design patterns, maybe trees, ect). It's hard to remember everything contained in this repository, however it's very easy to navigate and figure out as you go. It was created by Shawn who also happens to be writing most of the backend so he will be familiar with what to use which would be helpful. 

Learning Curve: 2/10

Usefulness: 8/10

Recommendations: I think this will save us time so we don't have to implement any of these functions ourselves. We probably won't use everything contained in Morgen Core since there is a lot, but I think it'd be useful to include in the project anyways to help shave off some of the work.

**Comment by TristanHeisler** [comment]
Observations:
- Tons and tons of java helper functions.

Learning Curve: 3/10
- Shawn made this. If we have any questions, I imagine he will be able to help us.

Usefulness: 9/10
- Tons of miscellaneous helper functions. Obviously, they are not all implemented yet, but a clear description of future planned features is presented.
- If the functionality exists, why reinvent the wheel?

Recommendations: 
I don't see why we would not use it. With Shawn being the author, it will be easier to understand what the tool is capable of doing. In the event of discovered bugs in the tool, it should hopefully be easier to get them resolved.
