### ISSUE TITLE
ReactJS Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#12]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by herasymj** [comment]
Observations:
While React seems more similar to classic programming languages (classes, inheritance, etc) the syntax is a little harder to pick up and understand than Vue. Documentation is pretty good overall, but again Vue has better documentation that is easier to understand. Started with the tutorial, but had to stop part way through because it doesn't teach you anything.

Learning Curve: 6/10

Userfulness: 9/10

Recommendation: While React and Vue seem to both be very useful, Vue just happens to be easier to understand for someone who's never used either before.
