### ISSUE TITLE
Evaluation of Vuex

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#37]
https://vuex.vuejs.org/getting-started.html

**Comment by TristanHeisler** [comment]
Observations:
- State management system for Vue
- Allows better management and tracking of states within the application

Learning Curve: 4/10
- The basic concept behind Vuex is quite simple.
- It took me a bit of time to actually get something up and running using Vuex. I think this may be partially due to the fact that I am still working on learning how to properly integrate all of these technologies

Usefulness: 6/10
- Assuming we have a sufficient use case for utilizing more in-depth state management, I see Vuex being useful.

Recommendations: 
- If we find that we require significant state management throughout the application, it will be worth considering using Vuex. Otherwise, it seems simply like extra boiler-plate.
