### ISSUE TITLE
TypeScript Evaluation

### ISSUE THREAD

**Issue by ShawnClake** [No-Patience/Planning#7]
* x/10 - Learning curve (Low is better)
* x/10 - Usefulness (High is better)
* Recommendation:

**Comment by ShawnClake** [comment]
Observations:
* Amazingly useful tool for creating Javascript classes and OOP code
* Typing everything is *annoying*, but it does seem to catch most errors prior to run-time.
* Awkward(..?) integration with VueJS, feels half baked
* Does provide solid IDE support for auto completion and bug catching

**Comment by TristanHeisler** [comment]
Observations:
- Webstorm has built in support for this, which is nice
- Compiles into normal JavaScript, but catches some errors prior to runtime
- Allows explicit typing of variables
- I found it difficult to incorporate and grasp it alongside Webpack/Vue/Bootstrap, etc, but I imagine that is my own lack of experience

Learning Curve: 7/10

Usefulness: 8/10

Recommendations: I believe it will be worth using since it extends the functionality of JavaScript and will ideally reduce the number of runtime errors by catching some at compile time.
